version: "3.8"
services: 
  api: 
    container_name: api-gateway
    restart: always
    build: .
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    depends_on:
      - db
    volumes: 
    - .:/usr/src/app

  db: 
    container_name: postgres
    image: postgres
    ports: 
      - "4321:${DB_PORT}"
    volumes: 
      - data:/data/db
    environment: 
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}

volumes:
  data: {}
